### ISSUE TITLE
Self chat feature

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk#311]
![image](https://user-images.githubusercontent.com/27461460/99874475-9500b700-2c2b-11eb-88ee-dcea96854656.png)

Most chat apps today have a feature to chat with the user himself. We currently have only friends.

We'd like to provide self chat features for note-taking or other purposes.

**Comment by qkreltms** [comment]
I wonder self chat feature is implemented in server?

**Comment by 0916dhkim** [comment]
Reopening

**Comment by 0916dhkim** [comment]
@qkreltms Many messenger apps create a self-chat room on initialization. As far as I know, Kakao and Telegram both generates self chat room automatically. Maybe Hackatalk can create self chat on user registration?

**Comment by hyochan** [comment]
> I wonder self chat feature is implemented in server? @hyochan

Not yet. We need to think about how can we provide this. My short idea is to provide another type in `ChannelType` which can be `self`.

```
enum ChannelType {
  private
  public
  self
}
```

I think we can create a `self` channel for the user if not exists

**Comment by rarira** [comment]
it seem more complicated because now `channels` query has `memberships(excludeMe: false)`. So if we try to add self channel with only one membership including me, we should change all the related codes.. for example, user thumbnail.

Now I'm trying to implement this by creating a self channel on user registration as suggested by @0916dhkim .

**Comment by hyochan** [comment]
Please check #459 as @qkreltms has pointed out!

It looks like we can handle UX and support this feature!

**Comment by hyochan** [comment]
Closing it as a dup #459
